### ISSUE TITLE
Running from docker

### ISSUE THREAD

**Issue by andrzejnovak** [DL4Jets/DeepJetCore#36]
@jkiesele New issue to not mix conda/docker

I am having trouble running from the docker image. It could be I'm doing something silly.
I log into a machine with GPU and run the docker image:
```
docker run -i -t cernml4reco/deepjetcore2:latest /bin/bash
```
 But there is no `nvidia-smi` and quickly trying 
```
python 
import setGPU
```
yields the following error:

```
Type "help", "copyright", "credits" or "license" for more information.
>>> import setGPU
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/setGPU.py", line 4, in <module>
    stats = gpustat.GPUStatCollection.new_query()
  File "/usr/local/lib/python2.7/dist-packages/gpustat/core.py", line 281, in new_query
    N.nvmlInit()
  File "/usr/local/lib/python2.7/dist-packages/pynvml.py", line 747, in nvmlInit
    _LoadNvmlLibrary()
  File "/usr/local/lib/python2.7/dist-packages/pynvml.py", line 785, in _LoadNvmlLibrary
    _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/usr/local/lib/python2.7/dist-packages/pynvml.py", line 405, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
```

I figured I would at least try to compile DeepJetCore, so I run:
```
git clone https://github.com/DL4Jets/DeepJetCore.git
cd DeepJetCore/compiled
make
```
which doesn't have the missing header problem like in conda, but ultimately fails as well:
```
to_bin/_testRaggedArray.cpp: In function 'int main()':
to_bin/_testRaggedArray.cpp:39:47: error: no matching function for call to 'djc::simpleArray<float>::simpleArray(<brace-enclosed initializer list>, std::vector<long unsigned int>&)'
     simpleArray<float> farr({4,-1,2},rowsplits);
                                               ^
In file included from to_bin/_testRaggedArray.cpp:5:0:
to_bin/../interface/simpleArray.h:283:1: note: candidate: djc::simpleArray<T>::simpleArray(djc::simpleArray<T>&&) [with T = float]
 simpleArray<T>::simpleArray(simpleArray<T> && a) :
 ^~~~~~~~~~~~~~
to_bin/../interface/simpleArray.h:283:1: note:   candidate expects 1 argument, 2 provided
to_bin/../interface/simpleArray.h:271:1: note: candidate: djc::simpleArray<T>::simpleArray(const djc::simpleArray<T>&) [with T = float]
 simpleArray<T>::simpleArray(const simpleArray<T>& a) :
 ^~~~~~~~~~~~~~
to_bin/../interface/simpleArray.h:271:1: note:   candidate expects 1 argument, 2 provided
to_bin/../interface/simpleArray.h:260:1: note: candidate: djc::simpleArray<T>::simpleArray(FILE*&) [with T = float; FILE = _IO_FILE]
 simpleArray<T>::simpleArray(FILE *& ifile):simpleArray<T>(){
 ^~~~~~~~~~~~~~
to_bin/../interface/simpleArray.h:260:1: note:   candidate expects 1 argument, 2 provided
to_bin/../interface/simpleArray.h:244:1: note: candidate: djc::simpleArray<T>::simpleArray(std::vector<int>, const std::vector<int>&) [with T = float]
 simpleArray<T>::simpleArray(std::vector<int> shape,const std::vector<int>& rowsplits) :
 ^~~~~~~~~~~~~~
to_bin/../interface/simpleArray.h:244:1: note:   no known conversion for argument 2 from 'std::vector<long unsigned int>' to 'const std::vector<int>&'
to_bin/../interface/simpleArray.h:239:1: note: candidate: djc::simpleArray<T>::simpleArray() [with T = float]
 simpleArray<T>::simpleArray() :
 ^~~~~~~~~~~~~~
to_bin/../interface/simpleArray.h:239:1: note:   candidate expects 0 arguments, 2 provided
Makefile:31: recipe for target '_testRaggedArray' failed
```

**Comment by andrzejnovak** [comment]
Also, a day or two later after requesting the e-group access, I still can't read `eos/home-j/jkiesele/singularity/run_deepjetcore2.sh`

**Comment by jkiesele** [comment]
Hi,

I see you in the member list - I will delete and add you again to be sure.
The Nvidia drivers come from the host system if I understand correctly (I only used the singularity images so far).
You can enable this according to the docker documentation with ‘docker run --gpus all … ‘.

As far as compiling is concerned, please use the release tag, not the HEAD (also indicated in the readme, at least since yesterday).

Jan

On 21 Nov 2019, at 17:36, Andrzej Novak <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, a day or two later after requesting the e-group access, I still can't read eos/home-j/jkiesele/singularity/run_deepjetcore2.sh

**Comment by jkiesele** [comment]
The test script error is fixed even in the HEAD Now:
2dcb5f61ac732beb5b7ecf48e864788c1d74fe7c

**Comment by andrzejnovak** [comment]
Hmm, seems the cluster I am working on doesn't have the nvidia-docker packages... Could you give me a few hints about singularity? I can finally access your `/eos` files so I copied the `.sif` file and try to run a similar script to what's in the `.sh` fille i.e.
```
singularity run -B /home -B /beegfs --bind /etc/krb5.conf:/etc/krb5.conf --bind /proc/fs/openafs/afs_ioctl:/proc/fs/openafs/afs_ioctl --bind /usr/vice/etc:/usr/vice/etc  --nv /beegfs/desy/user/anovak/newcore/deepjetcore2_latest.sif
```
But I get the following error 
```
FATAL:   container creation failed: hook function for tag sessiondir returns error: failed to read symlink /home/anovak/data/newcore: readlink /home/anovak/data/newcore: invalid argument
```
Which is kind of weird because `pwd` is not an input.

**Comment by andrzejnovak** [comment]
Ok, seems the cluster I am on doesn't have the required docker/nvidia packages. So I am trying to run with singularity.

I've managed to copy the `.sif` file and adapt the script from the `.sh` file to run 
```
singularity run -B /home -B /beegfs --bind /etc/krb5.conf:/etc/krb5.conf --bind /proc/fs/openafs/afs_ioctl:/proc/fs/openafs/afs_ioctl --bind /usr/vice/etc:/usr/vice/etc  --nv /beegfs/desy/user/anovak/newcore/deepjetcore2_latest.sif
```
which partially seems to work. I can import tensorflow and run on GPU. But compiling the modules still fails.

```
g++ -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /beegfs/desy/user/anovak/miniconda3/include `python-config --includes` `root-config  --cflags` -I./interface -O2 -fPIC -c -o obj/helper.o src/helper.cpp
In file included from src/helper.cpp:9:0:
src/../interface/helper.h:12:10: fatal error: boost/python.hpp: No such file or directory
 #include <boost/python.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:39: recipe for target 'obj/helper.o' failed
make: *** [obj/helper.o] Error 1
```

Happens regardless of master / 2.0 tag which makes sense. 

Could you elaborate a bit on what improvements are possible by moving from the conda setup?

**Comment by andrzejnovak** [comment]
@jkiesele bump, any idea why the `boost/python.hpp` should be missing if I run make within the singularity env?

**Comment by jkiesele** [comment]
I see a suspicious anaconda path there.
There is already an implicit mention of this in the readme:

"

It is important that your bashrc does not reset the LD_LIBRARY or PYTHONPATH environment variables.

"

I have added now explicitly one sentence for anaconda:

“

Also remove any anaconda paths from your bashrc, because they will reset LD_LIBRARY and PYTHONPATH. The system needs to be in a clean environment state within the container (as it should be).

“

Jan

On 4 Dec 2019, at 11:10, Andrzej Novak <notifications@github.com<mailto:notifications@github.com>> wrote:


@jkiesele<https://github.com/jkiesele> bump, any idea why the boost/python.hpp should be missing if I run make within the singularity env?
